import mod1
print(mod1.sum(4,7))
print(mod1.safe_sum("안녕",3))
# print(mod1.sum("안녕",3)) 에러발생
print(mod1.sum("안녕","hello"))